language: python

python:
  - 2.7
    
apt:
  packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    
script:
  - bash ./build_pyfvs.sh
  - make

deploy:
  - make install

branches:
  only:
    - module_refactor
