language: python

python:
  - "3.5"
    
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports

    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
#    - python3-numpy

script:
  - bash ./build_fvs.sh
  - cd bin/travis-ci && make -j2
  - cd pnc && bash ../../build_ext_py3.sh pnc
  - cd wcc && bash ../../build_ext_py3.sh wcc
