language: python

python:
  - "3.5"
  - "2.7"
    
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports

    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
#    - python3-numpy

env:
  global:
    - BUILD_ROOT=$PWD/$REPO/bin
    - PROJ_ROOT=$PWD/$REPO
    - F2PY=f2py
    
script:
  - cd $PROJ_ROOT && bash ./config_build.sh
  - cd $BUILD_ROOT/travis-ci && make -j2
  - cd $BUILD_ROOT/travis-ci/pnc && bash $BUILD_ROOT/build_ext_py3.sh pnc
  - cd $BUILD_ROOT/travis-ci/wcc && bash $BUILD_ROOT/build_ext_py3.sh wcc
