language: python

python:
  - "3.5"
    
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports

    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
#    - python3-numpy

script:
  - cd $HOME/build/tharen/PyFVS && bash $HOME/build/tharen/PyFVS/build_fvs.sh
  - cd $HOME/build/tharen/PyFVS/bin/travis-ci && make -j2
  - cd $HOME/build/tharen/PyFVS/bin/travis-ci/pnc && bash /home/travis/build/tharen/PyFVS/bin/build_ext_py3.sh pnc
  - cd $HOME/build/tharen/PyFVS/bin/travis-ci/wcc && bash /home/travis/build/tharen/PyFVS/bin/build_ext_py3.sh wcc
