language: python

python:
  - 3.5

addons:
  apt:
    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    
script:
  - bash ./build_pyfvs.sh
  - make

branches:
  only:
    - module_refactor
