language: python

python:
  - "2.7"
    
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - kubuntu-backports

    packages:
    - cmake
    - gfortran
    - unixodbc
    - unixodbc-dev
    - p7zip-full
    
script:
  - bash ./config_build.sh
  - cd bin
  - make -f makefile_all bundle

deploy:
  skip_cleanup: true
  
  script:
    - 7z a -bd open-fvs.zip Open-FVS/*
