# Drawing from: https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

version: 0.0.1-{build}

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    
  matrix:
    # - PYTHON: "C:\\Miniconda35-x64"
      # PYTHON_VERSION: "3.4" # NOTE: Not a typo, use support for Python 3.4
      # PYTHON_ARCH: "64"
      # ENV_NAME: "py34_x64_conda"

      # - PYTHON: "C:\\Python35-x64"
      # PYTHON_VERSION: "3.5.x"
      # PYTHON_ARCH: "64"
      # ENV_NAME: "py35_x64"

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      ENV_NAME: "py27_x64_conda"

    # - PYTHON: "C:\\Python27-x64"
      # PYTHON_VERSION: "2.7"
      # PYTHON_ARCH: "64"
      # ENV_NAME: "py27_x64"

init:
 # # Display remote desktop details
 # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - "echo %PYTHON_VERSION% %PYTHON%"
    
install:
    # Setup the python environment and install required packages
    # - cmd: .appveyor\\setup_env.bat
    - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - "conda create -q -n %ENV_NAME% python=%PYTHON_VERSION% numpy"    
    - conda info -a
    - activate %ENV_NAME%
    - pip install nose2 nose-parameterized cython
    
build_script:
    # Configure the CMake project and execute the build
    - cmd: .appveyor\\config_and_build.bat

after_build:
    # Create a zip file package of the compiled libraries and python package
    - "%APPVEYOR_BUILD_FOLDER%\\.appveyor\\bundle_archive.bat"

on_failure:
    # # Report remote desktop connection parameters and wait
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    # Post error logs to the build log
    - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\\bin\\build\\build_err.log
    - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\\bin\\build\\f2py.log

test_script:
    # Run tests against the final package
    - "%APPVEYOR_BUILD_FOLDER%\\.appveyor\\run_tests.bat"

after_test:
    # Build the wheel package
    - "%APPVEYOR_BUILD_FOLDER%\\.appveyor\\build_wheel.bat"
    - "dir %APPVEYOR_BUILD_FOLDER%\\artifacts"
    
artifacts:
    - path: open-fvs-*.zip
      name: open-fvs-zip
      type: zip
      
    - path: pyfvs*.whl
      name: pyfvs-wheel
      type: whl

deploy:
  - provider: GitHub
    # release: myproduct-v$(appveyor_build_version)
    description: 'Appveyor CI build.'
    auth_token:
      secure: kJTJhEXI8ycz28qE4v1LkJ54NZzrz0mVrSptvfliH7TFzXFPQG2Ojam2VWTJJb6s
    artifact: open-fvs-zip pyfvs-wheel # Using artifact name works consistently
    draft: false
    prerelease: true
    on:
      # branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only

  - provider: S3
    access_key_id: AKIAIVJ4GCLXEX2KK5QQ
    secret_access_key:
      secure: 3i/lHf5+t5tHVnX5dM/iHO9vOuvEZk65jCR94F1QSObHs8X5D1ZkY+BLW4fetlLC
    region: us-west-2
    bucket: free5
    set_public: true
    folder: appveyor-builds
    artifact: open-fvs-zip pyfvs-wheel

# on_finish:
  # # Pause the build for remote desktop access
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
